[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "Hypick"
name = "BetterShotgun"
description = "[v49] You can now buy a shotgun and ammo from the store or find them on the moons (Fully configurable)"
websiteUrl = "https://github.com/Hypick122/BetterShotgun"
containsNsfwContent = false

[package.dependencies]
# https://thunderstore.io/c/lethal-company/p/BepInEx/BepInExPack/
BepInEx-BepInExPack = "5.4.2100"
Evaisa-LethalLib = "0.14.1"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "BetterShotgun/bin/Hypick.BetterShotgun.dll"
target = "BetterShotgun.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
communities = ["lethal-company"]

[publish.categories]
# The categories are available at https://thunderstore.io near of the search bar
# https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = ["bepinex", "mods", "serverside", "equipment", "items"]
